apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: processador-pedidos
stringData:
  POSTGRES_DB: pedidosdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RABBIT_USER: guest
  RABBIT_PASS: guest
  DJANGO_SETTINGS_MODULE: config.settings
