apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel
  namespace: processador-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painel
  template:
    metadata:
      labels:
        app: painel
    spec:
      containers:
      - name: painel
        image: pedidos-app:v1
        imagePullPolicy: Never
        command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:3000", "--workers", "2"]
        envFrom:
        - secretRef:
            name: db-secret
        env:
        - name: DB_HOST
          value: db
---
apiVersion: v1
kind: Service
metadata:
  name: painel
  namespace: processador-pedidos
spec:
  type: NodePort
  selector:
    app: painel
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
